#!/usr/bin/env python
"""The Korean monk (zpMonkKorean, zpMonkKorean2): a mounted explorer on the vanilla Manchu horse archer model
(placeholder until a Korean retexture/model; owner 2026-10-09, the WoL mounted-monk principle).

Generated by tools/build.py, never edited by hand:

  art/units/korean_monk/korean_monk_horse.xml   vanilla manchurian_archer_horse animfile; the rider include points
  art/units/korean_monk/korean_monk_rider.xml   to the Korean rider copy; both get the animations the Japanese monk
                                                explorer rules ask for (data/tactics/zpmonkkorean.tactics): treasure
                                                pickup, building and smoke bomb from vanilla General Kichiro
                                                (DONOR_ANIMS), the rest as copies of Manchu animations (ALIASES)
  data/tactics/zpmonkkorean.tactics             vanilla ypjapanesemonk.tactics + the Dure aura (villagers near the
                                                monk gather faster; off until zpMonasteryDure)

Models, textures and animations are referenced by archive path, never copied. Kichiro is a mounted Asian hero on
the same horse and Bip01 rider rigs; his horse and rider blocks are copied as a matched pair (his horse stands while
the rider hammers), with the attachments they use. There is no mounted knockout animation in DE, so knockout shows
the idle pose (visual debt until a Korean model). tests/test_koreans.py fails when a tactics animation is missing
or plays the idle pose (owner 2026-10-09: the monk stood still while building and picking up treasure).

    python tools/korean_monk.py        # summary
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import korean_visuals  # noqa: E402  (BARTOOL)

BS = chr(92)
HORSE_SRC = 'Art/units/mercenaries/manchurian_archer/manchurian_archer_horse.xml.XMB'
RIDER_SRC = 'Art/units/mercenaries/manchurian_archer/manchurian_archer_rider.xml.XMB'
TACTICS_SRC = 'Data/tactics/ypjapanesemonk.tactics.XMB'
RIDER_VANILLA = BS.join(['units', 'mercenaries', 'manchurian_archer', 'manchurian_archer_rider.xml'])
RIDER_KOREAN = BS.join(['units', 'korean_monk', 'korean_monk_rider.xml'])
OUT_HORSE = 'art/units/korean_monk/korean_monk_horse.xml'
OUT_RIDER = 'art/units/korean_monk/korean_monk_rider.xml'
OUT_TACTICS = 'data/tactics/zpmonkkorean.tactics'
DONOR_HORSE = 'Art/units/asians/spc/kichiro/spc_kichiro_horse.xml.XMB'
DONOR_RIDER = 'Art/units/asians/spc/kichiro/spc_kichiro_rider.xml.XMB'

# animations copied from General Kichiro's horse and rider animfiles (matched pairs)
DONOR_ANIMS = ['Pickup', 'Build', 'BuildLifting', 'BuildSaw', 'BuildStaking', 'Smokescreen']

# animation the monk tactics use -> existing Manchu animation it copies
ALIASES = [
    ('Volley_standing_attack', 'Attack_ranged'),   # bow attacks and building attack
    ('stun_attack', 'Attack_ranged'),              # the stun shot
    ('Charge_attack', 'Attack_melee'),             # hand attacks
    ('Heal', 'Cheer'),
    ('Knockout', 'Idle'), ('KnockoutIdle', 'Idle'), ('Recover', 'Cheer'),   # no mounted knockout in DE
]

DURE = '''  <action>
    <name stringid="600018">Dure</name>
    <type>AutoRangedModify</type>
    <maxrange>16</maxrange>
    <active>0</active>
    <modifyabstracttype>AbstractVillager</modifyabstracttype>
    <persistent>1</persistent>
    <modifytype>GatherRate</modifytype>
    <modifymultiplier>1.10</modifymultiplier>
    <nostack>1</nostack>
  </action>
'''


def vanilla(path):
    out = subprocess.run([sys.executable, korean_visuals.BARTOOL, 'cat', path], capture_output=True, check=True)
    return out.stdout.decode('utf-8-sig').replace('\r\n', '\n')


def top_anim(text, name):
    """The top-level <anim>name ...</anim> block (2-space indent; anims inside attachments are skipped)."""
    m = re.search(r'^  <anim>%s<.*?^  </anim>\n' % re.escape(name), text, re.S | re.M)
    assert m, 'no top-level anim ' + name
    return m.group(0)


def add_donor_anims(text, donor):
    """Append the DONOR_ANIMS blocks of the donor animfile, plus the donor attachments they use that text lacks."""
    blocks = ''.join(top_anim(donor, name) for name in DONOR_ANIMS)
    have = set(re.findall(r'^  <attachment>(\w+)', text, re.M))
    extra = ''
    for name in dict.fromkeys(re.findall(r'<attach a="(\w+)"', blocks)):
        if name not in have:
            m = re.search(r'^  <attachment>%s<.*?^  </attachment>\n' % re.escape(name), donor, re.S | re.M)
            assert m, 'donor lacks attachment ' + name
            extra += m.group(0)
    if extra:                                      # attachments stand before the first component
        at = re.search(r'^  <component>', text, re.M).start()
        text = text[:at] + extra + text[at:]
    end = text.rindex('</animfile>')
    return text[:end] + blocks + text[end:]


def add_aliases(text):
    have = {a.lower() for a in re.findall(r'^  <anim>(\w+)', text, re.M)}
    blocks = []
    for new, src in ALIASES:
        if new.lower() in have:
            continue
        blocks.append(top_anim(text, src).replace('  <anim>%s<' % src, '  <anim>%s<' % new, 1))
    end = text.rindex('</animfile>')
    return text[:end] + ''.join(blocks) + text[end:]


def tactics():
    text = vanilla(TACTICS_SRC)
    first = re.search(r'^  <tactic>', text, re.M).start()
    text = text[:first] + DURE + text[first:]
    return re.sub(r'^(  <tactic>\w+)', r'\1<action>Dure</action>', text, flags=re.M)


def build():
    horse = vanilla(HORSE_SRC)
    assert horse.count(RIDER_VANILLA) == 1, 'rider include changed'
    horse = add_aliases(add_donor_anims(horse.replace(RIDER_VANILLA, RIDER_KOREAN), vanilla(DONOR_HORSE)))
    rider = add_aliases(add_donor_anims(vanilla(RIDER_SRC), vanilla(DONOR_RIDER)))
    out = {}
    for path, text in ((OUT_HORSE, horse), (OUT_RIDER, rider), (OUT_TACTICS, tactics())):
        out[path] = text.replace('\n', '\r\n').encode('utf-8')
    return out


def main():
    for path, data in build().items():
        print('%-45s %7d bytes' % (path, len(data)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
