#!/usr/bin/env python
"""The Korean monk (zpMonkKorean, zpMonkKorean2): a mounted monk-explorer (the WoL principle). Owner 2026-10-09: the
bald vanilla Shaolin Disciple on the yabusame rider skeleton (art/units/korean_monk/korean_monk_rider.gr2,
tools/korean_monk_model.py) riding the vanilla yabusame horse, retextured after the WoL Jeobju.

Generated by tools/build.py, never edited by hand:

  art/units/korean_monk/korean_monk_horse.xml   vanilla yabusame horse animfile: rider include -> the Korean rider,
                                                the hero cavalry selection decal of the Elmeti horse, the Manchu
                                                archer's tuned horse attacks (arrow leaves with the bow release),
                                                treasure pickup / building / smoke bomb from General Kichiro and
                                                the heal from the Lakota war chief (matched horse+rider pairs)
  art/units/korean_monk/korean_monk_rider.xml   vanilla yabusame rider animfile with the body models -> the Korean
                                                rider GR2; the same donor animations; aliases for the rest
  data/tactics/zpmonkkorean.tactics             vanilla ypjapanesemonk.tactics + the Dure aura (villagers near the
                                                monk gather faster; off until zpMonasteryDure)
  art/units/korean_monk/korean_seungbyeong.xml  the Seungbyeong (foot monk soldier, zpSeungbyeong): the vanilla Sohei
                                                animfile (glaive, pikeman.tactics animations) on the white-monk
                                                Disciple body (korean_seungbyeong.gr2): the animation library's
                                                Bip01 twins instead of the *_pikeman files, glaive on Bip01 Prop1

Models, textures and animations are referenced by archive path, never copied. All donors ride the same horse and
Bip01 rider rigs. There is no mounted knockout animation in DE, so knockout shows the idle pose (a known debt).
Guards in tests/test_koreans.py: every tactics animation exists and moves; the arrows leave with the bow release.
Method: AoP skill aoe3de-unit-animation.

    python tools/korean_monk.py        # summary
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import korean_visuals  # noqa: E402  (BARTOOL)

BS = chr(92)
HORSE_SRC = 'Art/units/asians/japanese/yabusame/yabusamehorse.xml.XMB'
RIDER_SRC = 'Art/units/asians/japanese/yabusame/yabusamerider.xml.XMB'
TACTICS_SRC = 'Data/tactics/ypjapanesemonk.tactics.XMB'
RIDER_VANILLA = BS.join(['units', 'asians', 'japanese', 'yabusame', 'yabusameRider.xml'])
RIDER_KOREAN = BS.join(['units', 'korean_monk', 'korean_monk_rider.xml'])
RIDER_MODEL = BS.join(['units', 'korean_monk', 'korean_monk_rider'])
BODY = re.compile(r'<file>units\\asians\\japanese\\yabusame\\yabusameRider_[02](_lp)?</file>', re.I)
OUT_HORSE = 'art/units/korean_monk/korean_monk_horse.xml'
OUT_RIDER = 'art/units/korean_monk/korean_monk_rider.xml'
OUT_TACTICS = 'data/tactics/zpmonkkorean.tactics'
SOHEI_SRC = 'Art/units/asians/japanese/sohei/sohei.xml.XMB'
SOHEI_BODY = re.compile(r'<file>units\\asians\\japanese\\sohei\\(lp_)?sohei_age2</file>', re.I)
FOOT_MODEL = BS.join(['units', 'korean_monk', 'korean_seungbyeong'])
OUT_FOOT = 'art/units/korean_monk/korean_seungbyeong.xml'

# Arrow sync (owner's game test 2026-10-09: "shooting anim is not well synced with the arrow"): the rider shoots with
# the generic cavalry bow_attack_A-D, whose release the generic horse_1-5_attack_A-D tags time (0.62 / 0.43 / 0.43 /
# 0.43, the Manchu archer pair); the yabusame's own horse attacks fire at 0.28, before the bow is drawn.
ATTACK_SRC = 'Art/units/mercenaries/manchurian_archer/manchurian_archer_horse.xml.XMB'
# hero cavalry selection (owner 2026-10-09: "swap the selection circle for cavalry hero one - check f.e. Elmeto"):
# hero shadow + hero selection ring on the cavalry oval, as the Elmeti horse
DECAL_SRC = 'Art/units/mercenaries/elmeti/elmeti_horse.xml.XMB'

# matched horse+rider animation pairs: (horse animfile, rider animfile, anim names, rider attachments to drop)
DONORS = [
    ('Art/units/asians/spc/kichiro/spc_kichiro_horse.xml.XMB', 'Art/units/asians/spc/kichiro/spc_kichiro_rider.xml.XMB',
     ['Pickup', 'Build', 'BuildLifting', 'BuildSaw', 'BuildStaking', 'Smokescreen'], ()),
    ('Art/units/natives/lakota/war_chief/war_chief_horse.xml.XMB', 'Art/units/natives/lakota/war_chief/war_chief_rider.xml.XMB',
     ['Heal'], ('spear',)),                                # the war chief's spear stays with him
]

# animation the monk tactics use -> existing animation it copies
ALIASES = [
    ('Volley_standing_attack', 'Attack_ranged'),   # bow attacks and building attack
    ('stun_attack', 'Attack_ranged'),              # the stun shot
    ('Charge_attack', 'Attack_melee'),             # hand attacks
    ('Knockout', 'Idle'), ('KnockoutIdle', 'Idle'), ('Recover', 'Cheer'),   # no mounted knockout in DE
]

DURE = '''  <action>
    <name stringid="600018">Dure</name>
    <type>AutoRangedModify</type>
    <maxrange>16</maxrange>
    <active>0</active>
    <modifyabstracttype>AbstractVillager</modifyabstracttype>
    <persistent>1</persistent>
    <modifytype>GatherRate</modifytype>
    <modifymultiplier>1.10</modifymultiplier>
    <nostack>1</nostack>
  </action>
'''


def vanilla(path):
    out = subprocess.run([sys.executable, korean_visuals.BARTOOL, 'cat', path], capture_output=True, check=True)
    return out.stdout.decode('utf-8-sig').replace('\r\n', '\n')


def top_anim(text, name):
    """The top-level <anim>name ...</anim> block (2-space indent; anims inside attachments are skipped)."""
    m = re.search(r'^  <anim>%s<.*?^  </anim>\n' % re.escape(name), text, re.S | re.M)
    assert m, 'no top-level anim ' + name
    return m.group(0)


def add_donor_anims(text, donor, names, drop=()):
    """Append the donor's blocks for `names` (minus `drop` attaches), plus the donor attachments they use."""
    blocks = ''
    for name in names:
        block = top_anim(donor, name)
        for a in drop:
            block = re.sub(r'^\s*<attach a="%s"[^>]*/>\n' % re.escape(a), '', block, flags=re.M)
        blocks += block
    have = set(re.findall(r'^  <attachment>(\w+)', text, re.M))
    extra = ''
    for name in dict.fromkeys(re.findall(r'<attach a="(\w+)"', blocks)):
        if name not in have:
            m = re.search(r'^  <attachment>%s<.*?^  </attachment>\n' % re.escape(name), donor, re.S | re.M)
            assert m, 'donor lacks attachment ' + name
            extra += m.group(0)
    if extra:                                      # attachments stand before the first component
        at = re.search(r'^  <component>', text, re.M).start()
        text = text[:at] + extra + text[at:]
    end = text.rindex('</animfile>')
    return text[:end] + blocks + text[end:]


def add_aliases(text):
    have = {a.lower() for a in re.findall(r'^  <anim>(\w+)', text, re.M)}
    blocks = []
    for new, src in ALIASES:
        if new.lower() in have:
            continue
        blocks.append(top_anim(text, src).replace('  <anim>%s<' % src, '  <anim>%s<' % new, 1))
    end = text.rindex('</animfile>')
    return text[:end] + ''.join(blocks) + text[end:]


def decal(text):
    m = re.search(r'^    <decal>.*?</decal>\n', text, re.S | re.M)
    assert m, 'no decal'
    return m.group(0)


def tactics():
    text = vanilla(TACTICS_SRC)
    first = re.search(r'^  <tactic>', text, re.M).start()
    text = text[:first] + DURE + text[first:]
    return re.sub(r'^(  <tactic>\w+)', r'\1<action>Dure</action>', text, flags=re.M)


def seungbyeong():
    """The Sohei's animfile on the Disciple body: same anims (the library's Bip01 twin of each *_pikeman file: the
    Disciple's bones are Bip01_*, the Sohei's Pikeman_*), same glaive, attached to the Disciple's Bip01 Prop1."""
    text, nbody = SOHEI_BODY.subn('<file>%s</file>' % FOOT_MODEL.replace(BS, BS * 2), vanilla(SOHEI_SRC))
    assert nbody == 2, 'expected the Sohei body and its low-poly model, found %d' % nbody
    text, nanim = re.subn(r'(<file>animation_library\\[^<]*)_pikeman</file>', r'\1</file>', text)
    assert nanim and '_pikeman</file>' not in text
    text = text.replace('Pikeman Prop1', 'Bip01 Prop1').replace('Pikeman Prop2', 'Bip01 Prop2')
    assert text.count('tobone="Bip01 Prop1"') == 2
    return text


def build():
    horse = vanilla(HORSE_SRC)
    assert horse.count(RIDER_VANILLA) == 1, 'yabusame rider include changed'
    horse = horse.replace(RIDER_VANILLA, RIDER_KOREAN)
    horse = horse.replace(top_anim(horse, 'Attack_ranged'), top_anim(vanilla(ATTACK_SRC), 'Attack_ranged'))
    horse = horse.replace(decal(horse), decal(vanilla(DECAL_SRC)))
    rider, nbody = BODY.subn('<file>%s</file>' % RIDER_MODEL.replace(BS, BS * 2), vanilla(RIDER_SRC))
    assert nbody == 4, 'expected the 4 yabusame body models (_0, _0_lp, _2, _2_lp), found %d' % nbody
    for horse_src, rider_src, names, drop in DONORS:
        horse = add_donor_anims(horse, vanilla(horse_src), names)
        rider = add_donor_anims(rider, vanilla(rider_src), names, drop)
    horse, rider = add_aliases(horse), add_aliases(rider)
    out = {}
    for path, text in ((OUT_HORSE, horse), (OUT_RIDER, rider), (OUT_TACTICS, tactics()), (OUT_FOOT, seungbyeong())):
        out[path] = text.replace('\n', '\r\n').encode('utf-8')
    return out


def main():
    for path, data in build().items():
        print('%-45s %7d bytes' % (path, len(data)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
